CREATE TABLE schedules (
    id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    subject_id INT NOT NULL,
    timetable DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_schedules_subjects FOREIGN KEY (subject_id) REFERENCES subjects(id)
);