DESCRIBE students;
-- CREATE TABLE students (
--     id VARCHAR(36) PRIMARY KEY NOT NULL,
--     nis VARCHAR(100) UNIQUE NOT NULL,
--     class_id INT NOT NULL,
--     name VARCHAR(100) NOT NULL,
--     status VARCHAR(20) NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--     CONSTRAINT fk_students_classes FOREIGN KEY(class_id) REFERENCES classes(id)
-- );